### PR TITLE
Run test files in random order to surface leaking state

### PR DESCRIPTION
**Pull request by lowellrex**
[Prior to the addition](https://github.com/department-of-veterans-affairs/caseflow-efolder/commit/a6fc320576376bb0fbc7ea312bc09af26df0a709#diff-cc581a8e6ec5512b31550fa03b0ba9f7) of the `User.authenticate!` call in help_spec.rb, the test would fail if run by itself because the user was not allowed to visit the particular page the test directs them to. However, this test failure was masked by the fact that the state of previous tests leaked into the help_spec.rb test allowing this test to pass when run after a test where the user had already authenticated.

Randomizing the test order does not solve the issue of leaking state, however, it will likely reveal tests that pass as a result of their position in the test plan.

### CODE REVIEW

**Comment by shanear** [comment]
and... it turns out that test wasn't the only one that was order dependent 😬

Awesome that we are finally airing all of these out.

**Comment by kierachell** [comment]
💪 RANDOMIZE ALL THE TESTS YASSSS

**Comment by nickheiner-usds** [comment]
Lololol yes, this was very easy. Thanks for doing this, @lowellrex!

**Comment by lowellrex** [comment]
Closing this out since it is not a priority at the moment.

**Pull request closed without merging**
