### PR TITLE
change padding to margin to fix underline

### PR DESCRIPTION
**Pull request by mmlumba**
Connects #573

### CODE REVIEW

**Comment by nemodjuric** [comment]
screen shot 2017-08-15 at 12 03 15 pm
screen shot 2017-08-15 at 12 00 56 pm

**Comment by nemodjuric** [comment]
@amprokop ^^

**Comment by amprokop** [comment]
@mmlumba @nemodjuric — does that mean that the focus is automatically assigned to the "Hide tutorial" link? in that case, are these coachmarks 508 accessible?

**Comment by mmlumba** [comment]
@amprokop Yes the coachmarks (both the bubble and the link to view them) are accessible.

**Comment by amprokop** [comment]
ok cool!

**Pull request merged**
