### PR TITLE
Remove v1 code

### PR DESCRIPTION
**Pull request by pkarman**
Replaces #1182 and connects #1095  

Still TODO:

- [ ] drop old tables
- [ ] remove feature toggles

### CODE REVIEW

**Comment by alisan16** [comment]
Is this related to #1095?

**Comment by aroltsch** [comment]
I left a comment in the slack thread last week that I've noticed there were a few files that could be deleted. Posting it here for visibility:

There are a few things left that we can delete:
1. v1 serializers
2. stats_controller.rb
3. controllers/api/v1/application_controller.rb

Also we should probably point jenkins to your branch and test efolder in uat

**Comment by pkarman** [comment]
> Is this related to #1095?

yes @alisan16

**Comment by pkarman** [comment]
@aroltsch and I tested this in preprod and found no regressions.

**Pull request merged**
