### PR TITLE
Toggle between median and 95th percentile statistics

### PR DESCRIPTION
**Pull request by cmgiven**

### CODE REVIEW

**Comment by shanear** [comment]
❤️ the code, but you need to update the feature spec to account for the new stuff (that's why the build is failing).

bonus points if you write a spec that toggles between median and 95%ile and checks that everything works 💯

**Comment by cmgiven** [comment]
Yup, that's what I get for rushing to get it in before I took off. Will update the specs.

**Comment by cmgiven** [comment]
@shanear: Back to you. Now without breaking all the things.

**Comment by shanear** [comment]
👍 🇺🇸

**Pull request merged**
