### PR TITLE
Drop old tables, remove old feature toggle

### PR DESCRIPTION
**Pull request by pkarman**
Finish removing v1 references.

connects #1095 #1224

### CODE REVIEW

**Comment by alisan16** [comment]
@yoomlam @hschallhorn Does Echo need any of these tables for ongoing metrics investigations into Reader? I know y'all were looking at caching of documents at some point, not sure if the tables in certification are sufficient or if you need anything from the efolder DB

**Comment by hschallhorn** [comment]
Not that I know of!

**Comment by pkarman** [comment]
The tables being dropped have not had any new data in them for 2+ years.

**Comment by yoomlam** [comment]
The document-related tables in certification are sufficient for my purposes.

**Pull request merged**
